linters:
  flake8:
    config: ./.flake8
    fixer: true

files:
  ignore:
    - 'node_modules/*'
    - 'tests/fixtures/black/*'
    - 'tests/fixtures/pep8/*'
    - 'tests/fixtures/py3k/*'
    - 'tests/fixtures/pytype/*'
    - 'tests/fixtures/rubocop/*'

fixers:
  enable: true
