linters:
  flake8:
    max-line-length: 100
  rubocop: {  }
ignore:
  files:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'tests/fixtures/black/*'
    - 'tests/fixtures/pep8/*'
    - 'tests/fixtures/py3k/*'
