linters:
  flake8:
    config: ./.flake8
  rubocop: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'tests/fixtures/black/*'
    - 'tests/fixtures/pep8/*'
    - 'tests/fixtures/py3k/*'
    - 'tests/fixtures/pytype/*'
    - 'tests/fixtures/rubocop/*'
