language: python

python: "2.7"

install:
  - pip install .
  - pip install codecov
  - pip install coverage

before_script:
  - npm install
  - bundle install --path ./bundle
  - cp settings.sample.py settings.py

env:
  - LINTREVIEW_SETTINGS="./settings.py"

script:
  - "nosetests --with-coverage"

after_success:
  - codecov

sudo: false

notifications:
  email:
    on_failure: change
