language: python

python: "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install golang

install:
  - pip install .
  - pip install codecov
  - pip install coverage

before_script:
  # install node and npm tools
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install 5
  - npm install

  # Use ruby2
  - rvm install 2.0.0
  - rvm use 2.0.0
  - bundle install --path ./bundle

  # Install golint
  - go get -u github.com/golang/lint/golint

  # Sample config file
  - cp settings.sample.py settings.py

env:
  - LINTREVIEW_SETTINGS="./settings.py" GOPATH="./gocode"

script:
  - nosetests --with-coverage --cover-package lintreview

after_success:
  - codecov

notifications:
  email:
    on_failure: change
