language: python

python: "2.7"

install:
  - pip install .
  - pip install codecov
  - pip install coverage

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_script:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 5 
  - npm install
  - bundle install --path ./bundle
  - cp settings.sample.py settings.py

env:
  - LINTREVIEW_SETTINGS="./settings.py"

script:
  - "nosetests --with-coverage"

after_success:
  - codecov

sudo: false

notifications:
  email:
    on_failure: change
