language: python
python:
 - "2.7"
install: "pip install ."
before_script:
  - npm install
  - bundle install --path ./bundle
  - pear install PHP_CodeSniffer
  - cp settings.sample.py settings.py
env:
  - LINTREVIEW_SETTINGS="./settings.py"
script: "nosetests"
notifications:
  email:
    on_failure: change
