---
language: python

services:
  - docker

addons:
  apt:
    packages:
      - gnupg2

python:
  - "3.6"
  - "3.8"

env:
  - LINTREVIEW_SETTINGS="./settings.py" GITHUB_OAUTH_TOKEN="fake-token-value"

before_install:
  - travis_wait make images
  - docker pull markstory/swiftlint
  - docker tag markstory/swiftlint swiftlint

install:
  - pip install -r requirements-dev.txt
  - pip install .
  # Sample config file
  - cp settings.sample.py settings.py

script:
  - >
    pytest -p no:cacheprovider \
      --cov=lintreview

after_success:
  - codecov

notifications:
  email:
    on_failure: change
