language: python
python:
 - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
before_script:
  - npm install jshint
  - npm install csslint
  - cp settings.sample.py settings.py
env:
  - LINTREVIEW_SETTINGS="./settings.py"
script: "nosetests"
notifications:
  email:
    on_failure: change
