language: python
python:
 - "2.7"
install: "pip install . --use-mirrors"
before_script:
  - npm install jshint
  - npm install csslint
  - gem install rubocop
  - gem install puppet-lint
  - cp settings.sample.py settings.py
env:
  - LINTREVIEW_SETTINGS="./settings.py"
script: "nosetests"
notifications:
  email:
    on_failure: change
