language: python
python:
 - "2.7"
install: "pip install -r requirements.txt --use-mirrors"
before_script:
  - npm install -g jshint
  - cp settings.sample.py settings.py
  - export=LINTREVIEW_SETTINGS=./settings.py
script: "nosetests"
notifications:
  email:
    on_failure: change
