broker:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
image:
  build: .
web:
  image: lintreview_image
  command: bash -c 'gunicorn -c /code/settings.py lintreview.web:app'
  environment:
    LINTREVIEW_GUNICORN_BIND: '0.0.0.0:5000'
  ports:
   - "5000:5000"
  links:
   - "broker:broker"
worker:
  image: lintreview_image
  environment:
    - C_FORCE_ROOT=true
  command: celery -A lintreview.tasks worker
  links:
   - "broker:broker"
